Repository Criqua/ManaguaFairs, pull requests merged in 2025-05, with the labels that each got.

#2 Creación de modelos y migraciones.
  app/Models/Emprendedor.php
  app/Models/Feria.php
  database/migrations/2025_05_13_201500_create_ferias_table.php
  database/migrations/2025_05_13_201505_create_emprendedores_table.php
  database/migrations/2025_05_13_203149_create_emprendedor_feria_table.php
  package-lock.json
Labels: documentation, good first issue

#4 Feature/controllers
  app/Http/Controllers/EmprendedorController.php
  app/Http/Controllers/FeriaController.php
  database/migrations/2025_05_14_050234_primera_migracion.php
  routes/web.php
Labels: enhancement

#5 (feat): add Blade view templates for fairs and entrepreneurs (index, create, edit & shared _form partial)
  resources/views/entrepreneurs/_form.blade.php
  resources/views/entrepreneurs/create.blade.php
  resources/views/entrepreneurs/edit.blade.php
  resources/views/entrepreneurs/index.blade.php
  resources/views/fairs/_form.blade.php
  resources/views/fairs/create.blade.php
  resources/views/fairs/edit.blade.php
  resources/views/fairs/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/navigation.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: enhancement

#6 Merge validated features from develop into main for stable release
  .env.example
  app/Http/Controllers/EntrepreneurController.php
  app/Http/Controllers/FairController.php
  app/Models/Entrepreneur.php
  app/Models/Fair.php
  database/migrations/2025_05_13_201500_create_fairs_table.php
  database/migrations/2025_05_13_201505_create_entrepreneurs_table.php
  database/migrations/2025_05_13_203149_create_fair_entrepreneur_table.php
  public/img/fair1.webp
  public/img/fair2.webp
  public/img/fair3.webp
  resources/views/dashboard.blade.php
  resources/views/entrepreneurs/_form.blade.php
  resources/views/entrepreneurs/create.blade.php
  resources/views/entrepreneurs/edit.blade.php
  resources/views/entrepreneurs/index.blade.php
  resources/views/fairs/_form.blade.php
  resources/views/fairs/create.blade.php
  resources/views/fairs/edit.blade.php
  resources/views/fairs/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/layouts/navigation.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tailwind.config.js
Labels: documentation, enhancement, stable
